[package]
name = "mirrormagic"
version = "0.1.0"
edition = "2021"

description = ""
# documentation = "..."
# homepage = "..."
repository = "https://github.com/Firstyear/mirrormagic"
readme = "README.md"
license = "MPL-2.0"

[dependencies]
tokio = { version = "1", features = ["rt", "net", "macros"] }
structopt = { version = "0.3", default-features = false }

tracing = "0.1"
tracing-subscriber = "0.3"

serde = { version = "1", features = ["derive"] }
